"""add observability fields to ai_enrichments

Revision ID: 2657b3ab2fde
Revises: dcf2684a465d
Create Date: 2026-04-14 16:54:46.270411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2657b3ab2fde'
down_revision: Union[str, None] = 'dcf2684a465d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_enrichments', sa.Column('prompt_version', sa.String(length=20), nullable=False))
    op.add_column('ai_enrichments', sa.Column('tokens_in', sa.Integer(), nullable=False))
    op.add_column('ai_enrichments', sa.Column('tokens_out', sa.Integer(), nullable=False))
    op.add_column('ai_enrichments', sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=False))
    op.add_column('ai_enrichments', sa.Column('raw_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_enrichments', 'raw_response')
    op.drop_column('ai_enrichments', 'estimated_cost')
    op.drop_column('ai_enrichments', 'tokens_out')
    op.drop_column('ai_enrichments', 'tokens_in')
    op.drop_column('ai_enrichments', 'prompt_version')
    # ### end Alembic commands ###
